spring:
  application:
    name: hexagonal
  datasource:
    url: jdbc:mysql://switchback.proxy.rlwy.net:44202/railway
    username: root
    password: nBLLizpayUQIqoRyVmBBTHXDsBfufbHz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # ELIMINAMOS la linea de database-platform para que Hibernate lo detecte solo
    properties:
      hibernate:
        format_sql: true

jackson:
  serialization:
    indent-output: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 9091